// Code generated by MockGen. DO NOT EDIT.
// Source: team-task-manager/internal/redis_rate_limiter (interfaces: ILimiter)

// Package ratelimiter is a generated GoMock package.
package ratelimiter

import (
	context "context"
	reflect "reflect"

	redis_rate "github.com/go-redis/redis_rate/v10"
	gomock "github.com/golang/mock/gomock"
)

// MockILimiter is a mock of ILimiter interface.
type MockILimiter struct {
	ctrl     *gomock.Controller
	recorder *MockILimiterMockRecorder
}

// MockILimiterMockRecorder is the mock recorder for MockILimiter.
type MockILimiterMockRecorder struct {
	mock *MockILimiter
}

// NewMockILimiter creates a new mock instance.
func NewMockILimiter(ctrl *gomock.Controller) *MockILimiter {
	mock := &MockILimiter{ctrl: ctrl}
	mock.recorder = &MockILimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILimiter) EXPECT() *MockILimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockILimiter) Allow(arg0 context.Context, arg1 string, arg2 redis_rate.Limit) (*redis_rate.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", arg0, arg1, arg2)
	ret0, _ := ret[0].(*redis_rate.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockILimiterMockRecorder) Allow(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockILimiter)(nil).Allow), arg0, arg1, arg2)
}
