// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addRefreshToken = `-- name: AddRefreshToken :exec
INSERT INTO refresh_tokens (token, user_id, expired_at, revoked, used)
VALUES (?, ?, ?, ?, ?)
`

type AddRefreshTokenParams struct {
	Token     string
	UserID    int64
	ExpiredAt time.Time
	Revoked   bool
	Used      bool
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, addRefreshToken,
		arg.Token,
		arg.UserID,
		arg.ExpiredAt,
		arg.Revoked,
		arg.Used,
	)
	return err
}

const cleanupUselessTokens = `-- name: CleanupUselessTokens :exec
DELETE FROM refresh_tokens 
WHERE expired_at < NOW() 
   OR (used = 1 AND created_at < DATE_SUB(NOW(), INTERVAL 1 DAY))
   OR (revoked = 1 AND created_at < DATE_SUB(NOW(), INTERVAL 1 DAY))
`

func (q *Queries) CleanupUselessTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupUselessTokens)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, name, role) VALUES (?, ?, ?)
`

type CreateUserParams struct {
	UserID int64
	Name   string
	Role   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.UserID, arg.Name, arg.Role)
	return err
}

const createUserAuth = `-- name: CreateUserAuth :execresult
INSERT INTO users_auth (login, password_hash) VALUES (?, ?)
`

type CreateUserAuthParams struct {
	Login        string
	PasswordHash string
}

func (q *Queries) CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserAuth, arg.Login, arg.PasswordHash)
}

const deleteUserSessions = `-- name: DeleteUserSessions :execresult
DELETE FROM refresh_tokens 
WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserSessions, userID)
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT token, user_id, expired_at, revoked, used
FROM refresh_tokens
WHERE token = ?
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiredAt,
		&i.Revoked,
		&i.Used,
	)
	return i, err
}

const getUserIdentitiesById = `-- name: GetUserIdentitiesById :one
SELECT 
    a.id, 
    a.login, 
    a.password_hash,
    u.name, 
    u.role
FROM users_auth a
INNER JOIN users u ON a.id = u.user_id
WHERE a.id = ?
LIMIT 1
`

type GetUserIdentitiesByIdRow struct {
	ID           int64
	Login        string
	PasswordHash string
	Name         string
	Role         string
}

func (q *Queries) GetUserIdentitiesById(ctx context.Context, id int64) (GetUserIdentitiesByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserIdentitiesById, id)
	var i GetUserIdentitiesByIdRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const getUserIdentitiesByLogin = `-- name: GetUserIdentitiesByLogin :one
SELECT 
    a.id, 
    a.login, 
    a.password_hash,
    u.name, 
    u.role
FROM users_auth a
INNER JOIN users u ON a.id = u.user_id
WHERE a.login = ?
LIMIT 1
`

type GetUserIdentitiesByLoginRow struct {
	ID           int64
	Login        string
	PasswordHash string
	Name         string
	Role         string
}

func (q *Queries) GetUserIdentitiesByLogin(ctx context.Context, login string) (GetUserIdentitiesByLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserIdentitiesByLogin, login)
	var i GetUserIdentitiesByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
	)
	return i, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :execresult
UPDATE refresh_tokens 
SET 
    expired_at = ?, 
    used = ?, 
    revoked = ?
WHERE token = ?
`

type UpdateRefreshTokenParams struct {
	ExpiredAt time.Time
	Used      bool
	Revoked   bool
	Token     string
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRefreshToken,
		arg.ExpiredAt,
		arg.Used,
		arg.Revoked,
		arg.Token,
	)
}
