// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type RefreshToken struct {
	Token     string
	UserID    int64
	ExpiredAt time.Time
	Revoked   bool
	Used      bool
}

type User struct {
	UserID int64
	Name   string
	Role   string
}

type UsersAuth struct {
	ID           int64
	Login        string
	PasswordHash string
}
