// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	Token     string
	UserID    int64
	ExpiredAt time.Time
	Revoked   bool
	Used      bool
}

type Task struct {
	TaskID      int64
	AssigneeID  int64
	CreatedBy   int64
	TeamID      int64
	Subject     string
	Description string
	CreatedAt   sql.NullTime
}

type Team struct {
	TeamID      int64
	OwnerID     int64
	Name        string
	Description string
}

type TeamMember struct {
	UserID   int64
	TeamID   int64
	JoinedAt sql.NullTime
}

type User struct {
	UserID int64
	Name   string
	Role   string
}

type UsersAuth struct {
	ID           int64
	Login        string
	PasswordHash string
}
