// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"
)

const getTasksAssigneeNotTeamMember = `-- name: GetTasksAssigneeNotTeamMember :many
SELECT t.task_id, t.assignee_id, t.created_by, t.team_id, t.subject, t.status, t.description, t.created_at, t.updated_at, t.version
FROM tasks t
	LEFT JOIN team_members tm ON t.team_id = tm.team_id AND t.assignee_id = tm.user_id
WHERE tm.user_id IS NULL
`

func (q *Queries) GetTasksAssigneeNotTeamMember(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksAssigneeNotTeamMember)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.TeamID,
			&i.Subject,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamTasksCompletedFor7Days = `-- name: GetTeamTasksCompletedFor7Days :many
SELECT t.name,
	   COALESCE(tm.members, 0) AS members,
	   COALESCE(ts.completed_in_7_days, 0) AS completed_in_7_days
FROM teams t
	LEFT JOIN
		(SELECT team_id, COUNT(*) AS members
		 FROM team_members
		 GROUP BY team_id) tm ON t.team_id = tm.team_id
	LEFT JOIN 
		(SELECT team_id, COUNT(*) completed_in_7_days
		 FROM tasks
		 WHERE status = "completed" 
		 	AND updated_at >= NOW() - INTERVAL 7 DAY
		 GROUP BY team_id) ts ON t.team_id = ts.team_id
`

type GetTeamTasksCompletedFor7DaysRow struct {
	Name             string
	Members          int64
	CompletedIn7Days int64
}

func (q *Queries) GetTeamTasksCompletedFor7Days(ctx context.Context) ([]GetTeamTasksCompletedFor7DaysRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamTasksCompletedFor7Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamTasksCompletedFor7DaysRow
	for rows.Next() {
		var i GetTeamTasksCompletedFor7DaysRow
		if err := rows.Scan(&i.Name, &i.Members, &i.CompletedIn7Days); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
