// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addNewTask = `-- name: AddNewTask :execresult
INSERT INTO tasks (assignee_id, created_by, team_id, subject, description, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddNewTaskParams struct {
	AssigneeID  int64
	CreatedBy   int64
	TeamID      int64
	Subject     string
	Description string
	Status      string
}

func (q *Queries) AddNewTask(ctx context.Context, arg AddNewTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addNewTask,
		arg.AssigneeID,
		arg.CreatedBy,
		arg.TeamID,
		arg.Subject,
		arg.Description,
		arg.Status,
	)
}

const getTasks = `-- name: GetTasks :many
SELECT task_id, 
    assignee_id,
    created_by,
    team_id,
    subject,
    status,
    description,
    created_at
FROM tasks
WHERE team_id = ?
  AND (status = ? OR ? IS NULL)
  AND (assignee_id = ? OR ? IS NULL)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetTasksParams struct {
	TeamID     int64
	Status     sql.NullString
	AssigneeID sql.NullInt64
	Limit      int32
	Offset     int32
}

func (q *Queries) GetTasks(ctx context.Context, arg GetTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks,
		arg.TeamID,
		arg.Status,
		arg.Status,
		arg.AssigneeID,
		arg.AssigneeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.TeamID,
			&i.Subject,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksOfTeam = `-- name: GetTasksOfTeam :many
SELECT task_id, 
    assignee_id,
    created_by,
    team_id,
    subject,
    status,
    description,
    created_at
FROM tasks
WHERE team_id = ?
`

func (q *Queries) GetTasksOfTeam(ctx context.Context, teamID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksOfTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.TeamID,
			&i.Subject,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTeamMember = `-- name: IsTeamMember :one
SELECT EXISTS(
    SELECT 1
    FROM team_members
    WHERE user_id = ? AND team_id = ?
)
`

type IsTeamMemberParams struct {
	UserID int64
	TeamID int64
}

func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTeamMember, arg.UserID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
