// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const addChangeToTaskHistory = `-- name: AddChangeToTaskHistory :execresult
INSERT INTO tasks_history (task_id, changed_by, payload)
VALUES (?, ?, ?)
`

type AddChangeToTaskHistoryParams struct {
	TaskID    int64
	ChangedBy int64
	Payload   json.RawMessage
}

func (q *Queries) AddChangeToTaskHistory(ctx context.Context, arg AddChangeToTaskHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addChangeToTaskHistory, arg.TaskID, arg.ChangedBy, arg.Payload)
}

const addNewTask = `-- name: AddNewTask :execresult
INSERT INTO tasks (assignee_id, created_by, team_id, subject, description, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddNewTaskParams struct {
	AssigneeID  int64
	CreatedBy   int64
	TeamID      int64
	Subject     string
	Description string
	Status      string
}

func (q *Queries) AddNewTask(ctx context.Context, arg AddNewTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addNewTask,
		arg.AssigneeID,
		arg.CreatedBy,
		arg.TeamID,
		arg.Subject,
		arg.Description,
		arg.Status,
	)
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT assignee_id, team_id, subject, status, description, version
FROM tasks 
WHERE task_id = ? 
FOR UPDATE
`

type GetTaskForUpdateRow struct {
	AssigneeID  int64
	TeamID      int64
	Subject     string
	Status      string
	Description string
	Version     int64
}

func (q *Queries) GetTaskForUpdate(ctx context.Context, taskID int64) (GetTaskForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskForUpdate, taskID)
	var i GetTaskForUpdateRow
	err := row.Scan(
		&i.AssigneeID,
		&i.TeamID,
		&i.Subject,
		&i.Status,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT task_id, 
    assignee_id,
    created_by,
    team_id,
    subject,
    status,
    description,
    created_at,
    version
FROM tasks
WHERE team_id = ?
  AND (status = ? OR ? IS NULL)
  AND (assignee_id = ? OR ? IS NULL)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetTasksParams struct {
	TeamID     int64
	Status     sql.NullString
	AssigneeID sql.NullInt64
	Limit      int32
	Offset     int32
}

func (q *Queries) GetTasks(ctx context.Context, arg GetTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks,
		arg.TeamID,
		arg.Status,
		arg.Status,
		arg.AssigneeID,
		arg.AssigneeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.TeamID,
			&i.Subject,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksOfTeam = `-- name: GetTasksOfTeam :many
SELECT task_id, 
    assignee_id,
    created_by,
    team_id,
    subject,
    status,
    description,
    created_at
FROM tasks
WHERE team_id = ?
`

type GetTasksOfTeamRow struct {
	TaskID      int64
	AssigneeID  int64
	CreatedBy   int64
	TeamID      int64
	Subject     string
	Status      string
	Description string
	CreatedAt   sql.NullTime
}

func (q *Queries) GetTasksOfTeam(ctx context.Context, teamID int64) ([]GetTasksOfTeamRow, error) {
	rows, err := q.db.QueryContext(ctx, getTasksOfTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksOfTeamRow
	for rows.Next() {
		var i GetTasksOfTeamRow
		if err := rows.Scan(
			&i.TaskID,
			&i.AssigneeID,
			&i.CreatedBy,
			&i.TeamID,
			&i.Subject,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTeamMember = `-- name: IsTeamMember :one
SELECT EXISTS(
    SELECT 1
    FROM team_members
    WHERE user_id = ? AND team_id = ?
)
`

type IsTeamMemberParams struct {
	UserID int64
	TeamID int64
}

func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTeamMember, arg.UserID, arg.TeamID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTask = `-- name: UpdateTask :execresult
UPDATE tasks 
SET assignee_id = ?,
    team_id = ?,
    subject = ?,
    status = ?,
    description = ?,
    version = version + 1
WHERE task_id = ?
`

type UpdateTaskParams struct {
	AssigneeID  int64
	TeamID      int64
	Subject     string
	Status      string
	Description string
	TaskID      int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTask,
		arg.AssigneeID,
		arg.TeamID,
		arg.Subject,
		arg.Status,
		arg.Description,
		arg.TaskID,
	)
}
