// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addMemberToTeam = `-- name: AddMemberToTeam :execresult
INSERT INTO team_members (user_id, team_id)
VALUES (?, ?)
`

type AddMemberToTeamParams struct {
	UserID int64
	TeamID int64
}

func (q *Queries) AddMemberToTeam(ctx context.Context, arg AddMemberToTeamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addMemberToTeam, arg.UserID, arg.TeamID)
}

const addNewTeam = `-- name: AddNewTeam :execresult
INSERT INTO teams (owner_id, name, description)
VALUES (?, ?, ?)
`

type AddNewTeamParams struct {
	OwnerID     int64
	Name        string
	Description string
}

func (q *Queries) AddNewTeam(ctx context.Context, arg AddNewTeamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addNewTeam, arg.OwnerID, arg.Name, arg.Description)
}

const getTeamOwner = `-- name: GetTeamOwner :one
select owner_id
FROM teams
WHERE team_id = ?
`

func (q *Queries) GetTeamOwner(ctx context.Context, teamID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeamOwner, teamID)
	var owner_id int64
	err := row.Scan(&owner_id)
	return owner_id, err
}

const getUserTeams = `-- name: GetUserTeams :many
SELECT t.team_id, t.name, t.description
FROM teams t
WHERE t.owner_id = ?
ORDER BY t.name
`

type GetUserTeamsRow struct {
	TeamID      int64
	Name        string
	Description string
}

func (q *Queries) GetUserTeams(ctx context.Context, ownerID int64) ([]GetUserTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeams, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTeamsRow
	for rows.Next() {
		var i GetUserTeamsRow
		if err := rows.Scan(&i.TeamID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
