// Code generated by MockGen. DO NOT EDIT.
// Source: team-task-manager/internal/api/v1 (interfaces: IAppService,IAuthService,ISecretProvider,IServer,IRouter,ILogger,ILimiter)

// Package api is a generated GoMock package.
package api

import (
	context "context"
	http "net/http"
	reflect "reflect"
	datastruct "team-task-manager/internal/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockIAppService is a mock of IAppService interface.
type MockIAppService struct {
	ctrl     *gomock.Controller
	recorder *MockIAppServiceMockRecorder
}

// MockIAppServiceMockRecorder is the mock recorder for MockIAppService.
type MockIAppServiceMockRecorder struct {
	mock *MockIAppService
}

// NewMockIAppService creates a new mock instance.
func NewMockIAppService(ctrl *gomock.Controller) *MockIAppService {
	mock := &MockIAppService{ctrl: ctrl}
	mock.recorder = &MockIAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAppService) EXPECT() *MockIAppServiceMockRecorder {
	return m.recorder
}

// AddNewTask mocks base method.
func (m *MockIAppService) AddNewTask(arg0 *datastruct.CreateTaskRequest) *datastruct.CreateTaskResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewTask", arg0)
	ret0, _ := ret[0].(*datastruct.CreateTaskResponse)
	return ret0
}

// AddNewTask indicates an expected call of AddNewTask.
func (mr *MockIAppServiceMockRecorder) AddNewTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewTask", reflect.TypeOf((*MockIAppService)(nil).AddNewTask), arg0)
}

// AddTaskComment mocks base method.
func (m *MockIAppService) AddTaskComment(arg0 *datastruct.AddTaskCommentRequest) *datastruct.AddTaskCommentResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskComment", arg0)
	ret0, _ := ret[0].(*datastruct.AddTaskCommentResponse)
	return ret0
}

// AddTaskComment indicates an expected call of AddTaskComment.
func (mr *MockIAppServiceMockRecorder) AddTaskComment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskComment", reflect.TypeOf((*MockIAppService)(nil).AddTaskComment), arg0)
}

// CreateTeam mocks base method.
func (m *MockIAppService) CreateTeam(arg0 *datastruct.CreateTeamRequest) *datastruct.CreateTeamResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", arg0)
	ret0, _ := ret[0].(*datastruct.CreateTeamResponse)
	return ret0
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockIAppServiceMockRecorder) CreateTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockIAppService)(nil).CreateTeam), arg0)
}

// GetTaskHistory mocks base method.
func (m *MockIAppService) GetTaskHistory(arg0 *datastruct.GetTaskHistoryRequest) *datastruct.GetTaskHistoryResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistory", arg0)
	ret0, _ := ret[0].(*datastruct.GetTaskHistoryResponse)
	return ret0
}

// GetTaskHistory indicates an expected call of GetTaskHistory.
func (mr *MockIAppServiceMockRecorder) GetTaskHistory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistory", reflect.TypeOf((*MockIAppService)(nil).GetTaskHistory), arg0)
}

// GetTasks mocks base method.
func (m *MockIAppService) GetTasks(arg0 *datastruct.GetTasksRequest) *datastruct.GetTasksResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", arg0)
	ret0, _ := ret[0].(*datastruct.GetTasksResponse)
	return ret0
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockIAppServiceMockRecorder) GetTasks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockIAppService)(nil).GetTasks), arg0)
}

// InviteUserToTeam mocks base method.
func (m *MockIAppService) InviteUserToTeam(arg0 *datastruct.InviteUserToTeamRequest) *datastruct.InviteUserToTeamResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InviteUserToTeam", arg0)
	ret0, _ := ret[0].(*datastruct.InviteUserToTeamResponse)
	return ret0
}

// InviteUserToTeam indicates an expected call of InviteUserToTeam.
func (mr *MockIAppServiceMockRecorder) InviteUserToTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InviteUserToTeam", reflect.TypeOf((*MockIAppService)(nil).InviteUserToTeam), arg0)
}

// ListUserTeams mocks base method.
func (m *MockIAppService) ListUserTeams(arg0 *datastruct.ListUserTeamsRequest) *datastruct.ListUserTeamsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserTeams", arg0)
	ret0, _ := ret[0].(*datastruct.ListUserTeamsResponse)
	return ret0
}

// ListUserTeams indicates an expected call of ListUserTeams.
func (mr *MockIAppServiceMockRecorder) ListUserTeams(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserTeams", reflect.TypeOf((*MockIAppService)(nil).ListUserTeams), arg0)
}

// UpdateTask mocks base method.
func (m *MockIAppService) UpdateTask(arg0 *datastruct.UpdateTaskRequest) *datastruct.UpdateTaskResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0)
	ret0, _ := ret[0].(*datastruct.UpdateTaskResponse)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockIAppServiceMockRecorder) UpdateTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockIAppService)(nil).UpdateTask), arg0)
}

// MockIAuthService is a mock of IAuthService interface.
type MockIAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthServiceMockRecorder
}

// MockIAuthServiceMockRecorder is the mock recorder for MockIAuthService.
type MockIAuthServiceMockRecorder struct {
	mock *MockIAuthService
}

// NewMockIAuthService creates a new mock instance.
func NewMockIAuthService(ctrl *gomock.Controller) *MockIAuthService {
	mock := &MockIAuthService{ctrl: ctrl}
	mock.recorder = &MockIAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthService) EXPECT() *MockIAuthServiceMockRecorder {
	return m.recorder
}

// LoginUser mocks base method.
func (m *MockIAuthService) LoginUser(arg0 *datastruct.LoginRequest) *datastruct.LoginResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0)
	ret0, _ := ret[0].(*datastruct.LoginResponse)
	return ret0
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockIAuthServiceMockRecorder) LoginUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockIAuthService)(nil).LoginUser), arg0)
}

// Refresh mocks base method.
func (m *MockIAuthService) Refresh(arg0 *datastruct.RefreshRequest) *datastruct.RefreshResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", arg0)
	ret0, _ := ret[0].(*datastruct.RefreshResponse)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockIAuthServiceMockRecorder) Refresh(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockIAuthService)(nil).Refresh), arg0)
}

// RegisterUser mocks base method.
func (m *MockIAuthService) RegisterUser(arg0 *datastruct.RegisterRequest) *datastruct.RegisterResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0)
	ret0, _ := ret[0].(*datastruct.RegisterResponse)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockIAuthServiceMockRecorder) RegisterUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockIAuthService)(nil).RegisterUser), arg0)
}

// MockISecretProvider is a mock of ISecretProvider interface.
type MockISecretProvider struct {
	ctrl     *gomock.Controller
	recorder *MockISecretProviderMockRecorder
}

// MockISecretProviderMockRecorder is the mock recorder for MockISecretProvider.
type MockISecretProviderMockRecorder struct {
	mock *MockISecretProvider
}

// NewMockISecretProvider creates a new mock instance.
func NewMockISecretProvider(ctrl *gomock.Controller) *MockISecretProvider {
	mock := &MockISecretProvider{ctrl: ctrl}
	mock.recorder = &MockISecretProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISecretProvider) EXPECT() *MockISecretProviderMockRecorder {
	return m.recorder
}

// ReadSecret mocks base method.
func (m *MockISecretProvider) ReadSecret(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSecret", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSecret indicates an expected call of ReadSecret.
func (mr *MockISecretProviderMockRecorder) ReadSecret(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSecret", reflect.TypeOf((*MockISecretProvider)(nil).ReadSecret), arg0)
}

// MockIServer is a mock of IServer interface.
type MockIServer struct {
	ctrl     *gomock.Controller
	recorder *MockIServerMockRecorder
}

// MockIServerMockRecorder is the mock recorder for MockIServer.
type MockIServerMockRecorder struct {
	mock *MockIServer
}

// NewMockIServer creates a new mock instance.
func NewMockIServer(ctrl *gomock.Controller) *MockIServer {
	mock := &MockIServer{ctrl: ctrl}
	mock.recorder = &MockIServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServer) EXPECT() *MockIServerMockRecorder {
	return m.recorder
}

// ListenAndServe mocks base method.
func (m *MockIServer) ListenAndServe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe")
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockIServerMockRecorder) ListenAndServe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockIServer)(nil).ListenAndServe))
}

// Shutdown mocks base method.
func (m *MockIServer) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockIServerMockRecorder) Shutdown(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockIServer)(nil).Shutdown), arg0)
}

// MockIRouter is a mock of IRouter interface.
type MockIRouter struct {
	ctrl     *gomock.Controller
	recorder *MockIRouterMockRecorder
}

// MockIRouterMockRecorder is the mock recorder for MockIRouter.
type MockIRouterMockRecorder struct {
	mock *MockIRouter
}

// NewMockIRouter creates a new mock instance.
func NewMockIRouter(ctrl *gomock.Controller) *MockIRouter {
	mock := &MockIRouter{ctrl: ctrl}
	mock.recorder = &MockIRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRouter) EXPECT() *MockIRouterMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockIRouter) Handle(arg0 string, arg1 http.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", arg0, arg1)
}

// Handle indicates an expected call of Handle.
func (mr *MockIRouterMockRecorder) Handle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockIRouter)(nil).Handle), arg0, arg1)
}

// ServeHTTP mocks base method.
func (m *MockIRouter) ServeHTTP(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", arg0, arg1)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockIRouterMockRecorder) ServeHTTP(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockIRouter)(nil).ServeHTTP), arg0, arg1)
}

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// ErrorKV mocks base method.
func (m *MockILogger) ErrorKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorKV", varargs...)
}

// ErrorKV indicates an expected call of ErrorKV.
func (mr *MockILoggerMockRecorder) ErrorKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorKV", reflect.TypeOf((*MockILogger)(nil).ErrorKV), varargs...)
}

// FatalKV mocks base method.
func (m *MockILogger) FatalKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FatalKV", varargs...)
}

// FatalKV indicates an expected call of FatalKV.
func (mr *MockILoggerMockRecorder) FatalKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FatalKV", reflect.TypeOf((*MockILogger)(nil).FatalKV), varargs...)
}

// InfoKV mocks base method.
func (m *MockILogger) InfoKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoKV", varargs...)
}

// InfoKV indicates an expected call of InfoKV.
func (mr *MockILoggerMockRecorder) InfoKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoKV", reflect.TypeOf((*MockILogger)(nil).InfoKV), varargs...)
}

// WarnKV mocks base method.
func (m *MockILogger) WarnKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnKV", varargs...)
}

// WarnKV indicates an expected call of WarnKV.
func (mr *MockILoggerMockRecorder) WarnKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnKV", reflect.TypeOf((*MockILogger)(nil).WarnKV), varargs...)
}

// MockILimiter is a mock of ILimiter interface.
type MockILimiter struct {
	ctrl     *gomock.Controller
	recorder *MockILimiterMockRecorder
}

// MockILimiterMockRecorder is the mock recorder for MockILimiter.
type MockILimiterMockRecorder struct {
	mock *MockILimiter
}

// NewMockILimiter creates a new mock instance.
func NewMockILimiter(ctrl *gomock.Controller) *MockILimiter {
	mock := &MockILimiter{ctrl: ctrl}
	mock.recorder = &MockILimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILimiter) EXPECT() *MockILimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockILimiter) Allow(arg0 string, arg1 int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockILimiterMockRecorder) Allow(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockILimiter)(nil).Allow), arg0, arg1)
}
