basePath: /api/v1
definitions:
  datastruct.CreateTaskRequest:
    properties:
      assignee_login:
        example: VaKadyk359
        type: string
      description:
        example: add new service endpoint
        type: string
      status:
        example: todo
        type: string
      subject:
        example: service endpoint
        type: string
      team_id:
        example: 1
        type: integer
    required:
    - assignee_login
    - description
    - status
    - subject
    - team_id
    type: object
  datastruct.CreateTaskResponse:
    properties:
      status:
        example: status message
        type: string
    type: object
  datastruct.CreateTeamRequest:
    properties:
      description:
        example: responsible for transactions
        type: string
      name:
        example: core
        type: string
    required:
    - description
    - name
    type: object
  datastruct.CreateTeamResponse:
    properties:
      status:
        example: status message
        type: string
    type: object
  datastruct.GetTaskHistoryResponse:
    properties:
      cached:
        example: false
        type: boolean
      status:
        example: status message
        type: string
      taskHistory:
        items:
          $ref: '#/definitions/datastruct.TaskOutput'
        type: array
    type: object
  datastruct.GetTasksResponse:
    properties:
      cached:
        example: false
        type: boolean
      status:
        example: status message
        type: string
      tasks:
        items:
          $ref: '#/definitions/datastruct.TaskOutput'
        type: array
    type: object
  datastruct.InviteUserToTeamRequest:
    properties:
      login:
        example: VaKadyk359
        type: string
    required:
    - login
    type: object
  datastruct.InviteUserToTeamResponse:
    properties:
      status:
        example: status message
        type: string
    type: object
  datastruct.ListUserTeamsResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/datastruct.TeamDescription'
        type: array
      status:
        example: status message
        type: string
    type: object
  datastruct.LoginRequest:
    properties:
      login:
        example: VaKadyk359
        type: string
      password:
        example: Xldf32Q
        type: string
    required:
    - login
    - password
    type: object
  datastruct.LoginResponse:
    properties:
      access_token:
        example: '-'
        type: string
      status:
        example: status message
        type: string
    type: object
  datastruct.RefreshResponse:
    properties:
      access_token:
        example: '-'
        type: string
      status:
        example: status message
        type: string
    type: object
  datastruct.RegisterRequest:
    properties:
      login:
        example: VaKadyk359
        type: string
      name:
        example: Vasilisa
        type: string
      password:
        example: Xldf32Q
        type: string
    required:
    - login
    - name
    - password
    type: object
  datastruct.RegisterResponse:
    properties:
      status:
        example: status message
        type: string
    type: object
  datastruct.Status:
    properties:
      status:
        example: status message
        type: string
    type: object
  datastruct.TaskOutput:
    properties:
      assignee_id:
        type: integer
      created_at:
        type: string
      created_by:
        type: integer
      description:
        type: string
      status:
        type: string
      subject:
        type: string
      task_id:
        type: integer
      team_id:
        type: integer
      version:
        type: integer
    type: object
  datastruct.TeamDescription:
    properties:
      description:
        example: responsible for transactions
        type: string
      name:
        example: core
        type: string
      team_id:
        example: 1
        type: integer
    required:
    - description
    - name
    - team_id
    type: object
  datastruct.UpdateTaskRequest:
    properties:
      assignee_login:
        example: VaKadyk359
        type: string
      description:
        example: add new service endpoint
        type: string
      status:
        example: todo
        type: string
      subject:
        example: service endpoint
        type: string
      task_id:
        example: 1
        type: integer
      team_id:
        example: 1
        type: integer
      version:
        example: 1
        type: integer
    required:
    - assignee_login
    - description
    - status
    - subject
    - task_id
    - team_id
    - version
    type: object
  datastruct.UpdateTaskResponse:
    properties:
      status:
        example: status message
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: hhullen@gmail.com
    name: Maksim
    url: https://github.com/hhullen
  description: Service for managing teams and tasks
  license:
    name: Creative Commons Attribution-NonCommercial 4.0 International Public License
    url: https://creativecommons.org/licenses/by-nc/4.0/deed.en
  termsOfService: http://swagger.io/terms/
  title: Team Task Manager
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: login user.
      parameters:
      - description: login and password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/datastruct.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      summary: login user
      tags:
      - Auth
  /refresh:
    post:
      description: refresh tokens.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.RefreshResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      summary: refresh tokens
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: register new user.
      parameters:
      - description: login and password and info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/datastruct.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      summary: register new user
      tags:
      - Auth
  /tasks:
    get:
      consumes:
      - application/json
      description: get tasks.
      parameters:
      - description: team_id
        example: "1"
        in: query
        name: team_id
        required: true
        type: string
      - description: status
        example: todo
        in: query
        name: status
        type: string
      - description: assignee_id
        example: "1"
        in: query
        name: assignee_id
        type: string
      - description: assignee_login
        example: VaKadyk359
        in: query
        name: assignee_login
        type: string
      - description: offset
        example: "0"
        in: query
        name: offset
        required: true
        type: string
      - description: limit
        example: "10"
        in: query
        name: limit
        required: true
        type: string
      - description: avoid_cache
        example: "true"
        in: query
        name: avoid_cache
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.GetTasksResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      security:
      - BearerAuth: []
      summary: get tasks
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: create new task.
      parameters:
      - description: task
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/datastruct.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.CreateTaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      security:
      - BearerAuth: []
      summary: create new task
      tags:
      - Tasks
  /tasks/{id}:
    put:
      consumes:
      - application/json
      description: update task.
      parameters:
      - description: team id
        in: path
        name: id
        required: true
        type: integer
      - description: task
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/datastruct.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.UpdateTaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      security:
      - BearerAuth: []
      summary: update task
      tags:
      - Tasks
  /tasks/{id}/history:
    get:
      consumes:
      - application/json
      description: get tasks history.
      parameters:
      - description: task_id
        example: 1
        in: path
        name: id
        required: true
        type: integer
      - description: avoid_cache
        example: "true"
        in: query
        name: avoid_cache
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.GetTaskHistoryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      security:
      - BearerAuth: []
      summary: get tasks history
      tags:
      - Tasks
  /teams:
    get:
      consumes:
      - application/json
      description: list teams the user member of .
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.ListUserTeamsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      security:
      - BearerAuth: []
      summary: list teams the user member of
      tags:
      - Teams
    post:
      consumes:
      - application/json
      description: create new team.
      parameters:
      - description: team description
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/datastruct.CreateTeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.CreateTeamResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      security:
      - BearerAuth: []
      summary: create new team
      tags:
      - Teams
  /teams/{id}/invite:
    post:
      consumes:
      - application/json
      description: invite user to team .
      parameters:
      - description: team id
        in: path
        name: id
        required: true
        type: integer
      - description: team id and login of invited user
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/datastruct.InviteUserToTeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datastruct.InviteUserToTeamResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datastruct.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datastruct.Status'
      security:
      - BearerAuth: []
      summary: invite user to team
      tags:
      - Teams
securityDefinitions:
  BearerAuth:
    description: Type 'Bearer <token>' to authenticate
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
