// Code generated by MockGen. DO NOT EDIT.
// Source: team-task-manager/internal/clients/mysql (interfaces: IQuerier,IDB,ILogger)

// Package mysql is a generated GoMock package.
package mysql

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	sqlc "team-task-manager/internal/clients/mysql/sqlc"

	gomock "github.com/golang/mock/gomock"
)

// MockIQuerier is a mock of IQuerier interface.
type MockIQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockIQuerierMockRecorder
}

// MockIQuerierMockRecorder is the mock recorder for MockIQuerier.
type MockIQuerierMockRecorder struct {
	mock *MockIQuerier
}

// NewMockIQuerier creates a new mock instance.
func NewMockIQuerier(ctrl *gomock.Controller) *MockIQuerier {
	mock := &MockIQuerier{ctrl: ctrl}
	mock.recorder = &MockIQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuerier) EXPECT() *MockIQuerierMockRecorder {
	return m.recorder
}

// AddChangeToTaskHistory mocks base method.
func (m *MockIQuerier) AddChangeToTaskHistory(arg0 context.Context, arg1 sqlc.AddChangeToTaskHistoryParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChangeToTaskHistory", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddChangeToTaskHistory indicates an expected call of AddChangeToTaskHistory.
func (mr *MockIQuerierMockRecorder) AddChangeToTaskHistory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChangeToTaskHistory", reflect.TypeOf((*MockIQuerier)(nil).AddChangeToTaskHistory), arg0, arg1)
}

// AddMemberToTeam mocks base method.
func (m *MockIQuerier) AddMemberToTeam(arg0 context.Context, arg1 sqlc.AddMemberToTeamParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemberToTeam", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMemberToTeam indicates an expected call of AddMemberToTeam.
func (mr *MockIQuerierMockRecorder) AddMemberToTeam(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemberToTeam", reflect.TypeOf((*MockIQuerier)(nil).AddMemberToTeam), arg0, arg1)
}

// AddNewTask mocks base method.
func (m *MockIQuerier) AddNewTask(arg0 context.Context, arg1 sqlc.AddNewTaskParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewTask", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewTask indicates an expected call of AddNewTask.
func (mr *MockIQuerierMockRecorder) AddNewTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewTask", reflect.TypeOf((*MockIQuerier)(nil).AddNewTask), arg0, arg1)
}

// AddNewTeam mocks base method.
func (m *MockIQuerier) AddNewTeam(arg0 context.Context, arg1 sqlc.AddNewTeamParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewTeam", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewTeam indicates an expected call of AddNewTeam.
func (mr *MockIQuerierMockRecorder) AddNewTeam(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewTeam", reflect.TypeOf((*MockIQuerier)(nil).AddNewTeam), arg0, arg1)
}

// AddRefreshToken mocks base method.
func (m *MockIQuerier) AddRefreshToken(arg0 context.Context, arg1 sqlc.AddRefreshTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRefreshToken indicates an expected call of AddRefreshToken.
func (mr *MockIQuerierMockRecorder) AddRefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRefreshToken", reflect.TypeOf((*MockIQuerier)(nil).AddRefreshToken), arg0, arg1)
}

// AddTaskComment mocks base method.
func (m *MockIQuerier) AddTaskComment(arg0 context.Context, arg1 sqlc.AddTaskCommentParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskComment", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTaskComment indicates an expected call of AddTaskComment.
func (mr *MockIQuerierMockRecorder) AddTaskComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskComment", reflect.TypeOf((*MockIQuerier)(nil).AddTaskComment), arg0, arg1)
}

// CleanupUselessTokens mocks base method.
func (m *MockIQuerier) CleanupUselessTokens(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupUselessTokens", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupUselessTokens indicates an expected call of CleanupUselessTokens.
func (mr *MockIQuerierMockRecorder) CleanupUselessTokens(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupUselessTokens", reflect.TypeOf((*MockIQuerier)(nil).CleanupUselessTokens), arg0)
}

// CreateUser mocks base method.
func (m *MockIQuerier) CreateUser(arg0 context.Context, arg1 sqlc.CreateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIQuerierMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIQuerier)(nil).CreateUser), arg0, arg1)
}

// CreateUserAuth mocks base method.
func (m *MockIQuerier) CreateUserAuth(arg0 context.Context, arg1 sqlc.CreateUserAuthParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAuth", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAuth indicates an expected call of CreateUserAuth.
func (mr *MockIQuerierMockRecorder) CreateUserAuth(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAuth", reflect.TypeOf((*MockIQuerier)(nil).CreateUserAuth), arg0, arg1)
}

// DeleteUserSessions mocks base method.
func (m *MockIQuerier) DeleteUserSessions(arg0 context.Context, arg1 int64) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSessions", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserSessions indicates an expected call of DeleteUserSessions.
func (mr *MockIQuerierMockRecorder) DeleteUserSessions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSessions", reflect.TypeOf((*MockIQuerier)(nil).DeleteUserSessions), arg0, arg1)
}

// GetRefreshToken mocks base method.
func (m *MockIQuerier) GetRefreshToken(arg0 context.Context, arg1 string) (sqlc.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(sqlc.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockIQuerierMockRecorder) GetRefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockIQuerier)(nil).GetRefreshToken), arg0, arg1)
}

// GetTask mocks base method.
func (m *MockIQuerier) GetTask(arg0 context.Context, arg1 int64) (sqlc.GetTaskRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1)
	ret0, _ := ret[0].(sqlc.GetTaskRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockIQuerierMockRecorder) GetTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockIQuerier)(nil).GetTask), arg0, arg1)
}

// GetTaskForUpdate mocks base method.
func (m *MockIQuerier) GetTaskForUpdate(arg0 context.Context, arg1 int64) (sqlc.GetTaskForUpdateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskForUpdate", arg0, arg1)
	ret0, _ := ret[0].(sqlc.GetTaskForUpdateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskForUpdate indicates an expected call of GetTaskForUpdate.
func (mr *MockIQuerierMockRecorder) GetTaskForUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskForUpdate", reflect.TypeOf((*MockIQuerier)(nil).GetTaskForUpdate), arg0, arg1)
}

// GetTaskHistory mocks base method.
func (m *MockIQuerier) GetTaskHistory(arg0 context.Context, arg1 sqlc.GetTaskHistoryParams) ([]sqlc.GetTaskHistoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistory", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.GetTaskHistoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistory indicates an expected call of GetTaskHistory.
func (mr *MockIQuerierMockRecorder) GetTaskHistory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistory", reflect.TypeOf((*MockIQuerier)(nil).GetTaskHistory), arg0, arg1)
}

// GetTasks mocks base method.
func (m *MockIQuerier) GetTasks(arg0 context.Context, arg1 sqlc.GetTasksParams) ([]sqlc.GetTasksRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.GetTasksRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockIQuerierMockRecorder) GetTasks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockIQuerier)(nil).GetTasks), arg0, arg1)
}

// GetTasksAssigneeNotTeamMember mocks base method.
func (m *MockIQuerier) GetTasksAssigneeNotTeamMember(arg0 context.Context) ([]sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksAssigneeNotTeamMember", arg0)
	ret0, _ := ret[0].([]sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksAssigneeNotTeamMember indicates an expected call of GetTasksAssigneeNotTeamMember.
func (mr *MockIQuerierMockRecorder) GetTasksAssigneeNotTeamMember(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksAssigneeNotTeamMember", reflect.TypeOf((*MockIQuerier)(nil).GetTasksAssigneeNotTeamMember), arg0)
}

// GetTasksComments mocks base method.
func (m *MockIQuerier) GetTasksComments(arg0 context.Context, arg1 []int64) ([]sqlc.TasksComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksComments", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.TasksComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksComments indicates an expected call of GetTasksComments.
func (mr *MockIQuerierMockRecorder) GetTasksComments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksComments", reflect.TypeOf((*MockIQuerier)(nil).GetTasksComments), arg0, arg1)
}

// GetTasksOfTeam mocks base method.
func (m *MockIQuerier) GetTasksOfTeam(arg0 context.Context, arg1 int64) ([]sqlc.GetTasksOfTeamRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksOfTeam", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.GetTasksOfTeamRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksOfTeam indicates an expected call of GetTasksOfTeam.
func (mr *MockIQuerierMockRecorder) GetTasksOfTeam(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksOfTeam", reflect.TypeOf((*MockIQuerier)(nil).GetTasksOfTeam), arg0, arg1)
}

// GetTeamOwner mocks base method.
func (m *MockIQuerier) GetTeamOwner(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamOwner", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamOwner indicates an expected call of GetTeamOwner.
func (mr *MockIQuerierMockRecorder) GetTeamOwner(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamOwner", reflect.TypeOf((*MockIQuerier)(nil).GetTeamOwner), arg0, arg1)
}

// GetTeamTasksCompletedFor7Days mocks base method.
func (m *MockIQuerier) GetTeamTasksCompletedFor7Days(arg0 context.Context) ([]sqlc.GetTeamTasksCompletedFor7DaysRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamTasksCompletedFor7Days", arg0)
	ret0, _ := ret[0].([]sqlc.GetTeamTasksCompletedFor7DaysRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamTasksCompletedFor7Days indicates an expected call of GetTeamTasksCompletedFor7Days.
func (mr *MockIQuerierMockRecorder) GetTeamTasksCompletedFor7Days(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamTasksCompletedFor7Days", reflect.TypeOf((*MockIQuerier)(nil).GetTeamTasksCompletedFor7Days), arg0)
}

// GetUserIdentitiesById mocks base method.
func (m *MockIQuerier) GetUserIdentitiesById(arg0 context.Context, arg1 int64) (sqlc.GetUserIdentitiesByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdentitiesById", arg0, arg1)
	ret0, _ := ret[0].(sqlc.GetUserIdentitiesByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdentitiesById indicates an expected call of GetUserIdentitiesById.
func (mr *MockIQuerierMockRecorder) GetUserIdentitiesById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdentitiesById", reflect.TypeOf((*MockIQuerier)(nil).GetUserIdentitiesById), arg0, arg1)
}

// GetUserIdentitiesByLogin mocks base method.
func (m *MockIQuerier) GetUserIdentitiesByLogin(arg0 context.Context, arg1 string) (sqlc.GetUserIdentitiesByLoginRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdentitiesByLogin", arg0, arg1)
	ret0, _ := ret[0].(sqlc.GetUserIdentitiesByLoginRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdentitiesByLogin indicates an expected call of GetUserIdentitiesByLogin.
func (mr *MockIQuerierMockRecorder) GetUserIdentitiesByLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdentitiesByLogin", reflect.TypeOf((*MockIQuerier)(nil).GetUserIdentitiesByLogin), arg0, arg1)
}

// GetUserTeams mocks base method.
func (m *MockIQuerier) GetUserTeams(arg0 context.Context, arg1 int64) ([]sqlc.GetUserTeamsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTeams", arg0, arg1)
	ret0, _ := ret[0].([]sqlc.GetUserTeamsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTeams indicates an expected call of GetUserTeams.
func (mr *MockIQuerierMockRecorder) GetUserTeams(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTeams", reflect.TypeOf((*MockIQuerier)(nil).GetUserTeams), arg0, arg1)
}

// IsTeamMember mocks base method.
func (m *MockIQuerier) IsTeamMember(arg0 context.Context, arg1 sqlc.IsTeamMemberParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTeamMember", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTeamMember indicates an expected call of IsTeamMember.
func (mr *MockIQuerierMockRecorder) IsTeamMember(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTeamMember", reflect.TypeOf((*MockIQuerier)(nil).IsTeamMember), arg0, arg1)
}

// UpdateRefreshToken mocks base method.
func (m *MockIQuerier) UpdateRefreshToken(arg0 context.Context, arg1 sqlc.UpdateRefreshTokenParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRefreshToken indicates an expected call of UpdateRefreshToken.
func (mr *MockIQuerierMockRecorder) UpdateRefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockIQuerier)(nil).UpdateRefreshToken), arg0, arg1)
}

// UpdateTask mocks base method.
func (m *MockIQuerier) UpdateTask(arg0 context.Context, arg1 sqlc.UpdateTaskParams) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockIQuerierMockRecorder) UpdateTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockIQuerier)(nil).UpdateTask), arg0, arg1)
}

// MockIDB is a mock of IDB interface.
type MockIDB struct {
	ctrl     *gomock.Controller
	recorder *MockIDBMockRecorder
}

// MockIDBMockRecorder is the mock recorder for MockIDB.
type MockIDBMockRecorder struct {
	mock *MockIDB
}

// NewMockIDB creates a new mock instance.
func NewMockIDB(ctrl *gomock.Controller) *MockIDB {
	mock := &MockIDB{ctrl: ctrl}
	mock.recorder = &MockIDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDB) EXPECT() *MockIDBMockRecorder {
	return m.recorder
}

// CtxWithCancel mocks base method.
func (m *MockIDB) CtxWithCancel() (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxWithCancel")
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// CtxWithCancel indicates an expected call of CtxWithCancel.
func (mr *MockIDBMockRecorder) CtxWithCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxWithCancel", reflect.TypeOf((*MockIDB)(nil).CtxWithCancel))
}

// ExecTx mocks base method.
func (m *MockIDB) ExecTx(arg0 *sql.TxOptions, arg1 func(context.Context, IQuerier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockIDBMockRecorder) ExecTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockIDB)(nil).ExecTx), arg0, arg1)
}

// Querier mocks base method.
func (m *MockIDB) Querier() IQuerier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Querier")
	ret0, _ := ret[0].(IQuerier)
	return ret0
}

// Querier indicates an expected call of Querier.
func (mr *MockIDBMockRecorder) Querier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Querier", reflect.TypeOf((*MockIDB)(nil).Querier))
}

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// InfoKV mocks base method.
func (m *MockILogger) InfoKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoKV", varargs...)
}

// InfoKV indicates an expected call of InfoKV.
func (mr *MockILoggerMockRecorder) InfoKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoKV", reflect.TypeOf((*MockILogger)(nil).InfoKV), varargs...)
}
