// Code generated by MockGen. DO NOT EDIT.
// Source: team-task-manager/internal/service (interfaces: ILogger,ICache,ICachedState,IAuthStorage,IAppStorage,ISecretProvider)

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"
	datastruct "team-task-manager/internal/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// ErrorKV mocks base method.
func (m *MockILogger) ErrorKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorKV", varargs...)
}

// ErrorKV indicates an expected call of ErrorKV.
func (mr *MockILoggerMockRecorder) ErrorKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorKV", reflect.TypeOf((*MockILogger)(nil).ErrorKV), varargs...)
}

// FatalKV mocks base method.
func (m *MockILogger) FatalKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FatalKV", varargs...)
}

// FatalKV indicates an expected call of FatalKV.
func (mr *MockILoggerMockRecorder) FatalKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FatalKV", reflect.TypeOf((*MockILogger)(nil).FatalKV), varargs...)
}

// InfoKV mocks base method.
func (m *MockILogger) InfoKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoKV", varargs...)
}

// InfoKV indicates an expected call of InfoKV.
func (mr *MockILoggerMockRecorder) InfoKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoKV", reflect.TypeOf((*MockILogger)(nil).InfoKV), varargs...)
}

// WarnKV mocks base method.
func (m *MockILogger) WarnKV(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnKV", varargs...)
}

// WarnKV indicates an expected call of WarnKV.
func (mr *MockILoggerMockRecorder) WarnKV(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnKV", reflect.TypeOf((*MockILogger)(nil).WarnKV), varargs...)
}

// MockICache is a mock of ICache interface.
type MockICache struct {
	ctrl     *gomock.Controller
	recorder *MockICacheMockRecorder
}

// MockICacheMockRecorder is the mock recorder for MockICache.
type MockICacheMockRecorder struct {
	mock *MockICache
}

// NewMockICache creates a new mock instance.
func NewMockICache(ctrl *gomock.Controller) *MockICache {
	mock := &MockICache{ctrl: ctrl}
	mock.recorder = &MockICacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICache) EXPECT() *MockICacheMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockICache) Read(arg0 string, arg1 interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockICacheMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockICache)(nil).Read), arg0, arg1)
}

// Write mocks base method.
func (m *MockICache) Write(arg0 string, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockICacheMockRecorder) Write(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockICache)(nil).Write), arg0, arg1)
}

// MockICachedState is a mock of ICachedState interface.
type MockICachedState struct {
	ctrl     *gomock.Controller
	recorder *MockICachedStateMockRecorder
}

// MockICachedStateMockRecorder is the mock recorder for MockICachedState.
type MockICachedStateMockRecorder struct {
	mock *MockICachedState
}

// NewMockICachedState creates a new mock instance.
func NewMockICachedState(ctrl *gomock.Controller) *MockICachedState {
	mock := &MockICachedState{ctrl: ctrl}
	mock.recorder = &MockICachedStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICachedState) EXPECT() *MockICachedStateMockRecorder {
	return m.recorder
}

// SetCached mocks base method.
func (m *MockICachedState) SetCached(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCached", arg0)
}

// SetCached indicates an expected call of SetCached.
func (mr *MockICachedStateMockRecorder) SetCached(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCached", reflect.TypeOf((*MockICachedState)(nil).SetCached), arg0)
}

// MockIAuthStorage is a mock of IAuthStorage interface.
type MockIAuthStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthStorageMockRecorder
}

// MockIAuthStorageMockRecorder is the mock recorder for MockIAuthStorage.
type MockIAuthStorageMockRecorder struct {
	mock *MockIAuthStorage
}

// NewMockIAuthStorage creates a new mock instance.
func NewMockIAuthStorage(ctrl *gomock.Controller) *MockIAuthStorage {
	mock := &MockIAuthStorage{ctrl: ctrl}
	mock.recorder = &MockIAuthStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthStorage) EXPECT() *MockIAuthStorageMockRecorder {
	return m.recorder
}

// AddNewUser mocks base method.
func (m *MockIAuthStorage) AddNewUser(arg0 *datastruct.DBRegisterRequest) (*datastruct.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewUser", arg0)
	ret0, _ := ret[0].(*datastruct.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewUser indicates an expected call of AddNewUser.
func (mr *MockIAuthStorageMockRecorder) AddNewUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewUser", reflect.TypeOf((*MockIAuthStorage)(nil).AddNewUser), arg0)
}

// AddRefreshToken mocks base method.
func (m *MockIAuthStorage) AddRefreshToken(arg0 *datastruct.DBRefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRefreshToken", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRefreshToken indicates an expected call of AddRefreshToken.
func (mr *MockIAuthStorageMockRecorder) AddRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRefreshToken", reflect.TypeOf((*MockIAuthStorage)(nil).AddRefreshToken), arg0)
}

// CleanupUslessTokens mocks base method.
func (m *MockIAuthStorage) CleanupUslessTokens() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupUslessTokens")
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupUslessTokens indicates an expected call of CleanupUslessTokens.
func (mr *MockIAuthStorageMockRecorder) CleanupUslessTokens() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupUslessTokens", reflect.TypeOf((*MockIAuthStorage)(nil).CleanupUslessTokens))
}

// DeleteAllUserSession mocks base method.
func (m *MockIAuthStorage) DeleteAllUserSession(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUserSession", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllUserSession indicates an expected call of DeleteAllUserSession.
func (mr *MockIAuthStorageMockRecorder) DeleteAllUserSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUserSession", reflect.TypeOf((*MockIAuthStorage)(nil).DeleteAllUserSession), arg0)
}

// GetAuthIdentitiesByLogin mocks base method.
func (m *MockIAuthStorage) GetAuthIdentitiesByLogin(arg0 string) (*datastruct.AuthIdentities, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthIdentitiesByLogin", arg0)
	ret0, _ := ret[0].(*datastruct.AuthIdentities)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAuthIdentitiesByLogin indicates an expected call of GetAuthIdentitiesByLogin.
func (mr *MockIAuthStorageMockRecorder) GetAuthIdentitiesByLogin(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthIdentitiesByLogin", reflect.TypeOf((*MockIAuthStorage)(nil).GetAuthIdentitiesByLogin), arg0)
}

// GetAuthIdentitiesByUserID mocks base method.
func (m *MockIAuthStorage) GetAuthIdentitiesByUserID(arg0 int64) (*datastruct.AuthIdentities, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthIdentitiesByUserID", arg0)
	ret0, _ := ret[0].(*datastruct.AuthIdentities)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAuthIdentitiesByUserID indicates an expected call of GetAuthIdentitiesByUserID.
func (mr *MockIAuthStorageMockRecorder) GetAuthIdentitiesByUserID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthIdentitiesByUserID", reflect.TypeOf((*MockIAuthStorage)(nil).GetAuthIdentitiesByUserID), arg0)
}

// GetRefreshToken mocks base method.
func (m *MockIAuthStorage) GetRefreshToken(arg0 string) (*datastruct.DBRefreshToken, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", arg0)
	ret0, _ := ret[0].(*datastruct.DBRefreshToken)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockIAuthStorageMockRecorder) GetRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockIAuthStorage)(nil).GetRefreshToken), arg0)
}

// UpdateRefreshToken mocks base method.
func (m *MockIAuthStorage) UpdateRefreshToken(arg0 *datastruct.DBUpdateRefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshToken indicates an expected call of UpdateRefreshToken.
func (mr *MockIAuthStorageMockRecorder) UpdateRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockIAuthStorage)(nil).UpdateRefreshToken), arg0)
}

// MockIAppStorage is a mock of IAppStorage interface.
type MockIAppStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIAppStorageMockRecorder
}

// MockIAppStorageMockRecorder is the mock recorder for MockIAppStorage.
type MockIAppStorageMockRecorder struct {
	mock *MockIAppStorage
}

// NewMockIAppStorage creates a new mock instance.
func NewMockIAppStorage(ctrl *gomock.Controller) *MockIAppStorage {
	mock := &MockIAppStorage{ctrl: ctrl}
	mock.recorder = &MockIAppStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAppStorage) EXPECT() *MockIAppStorageMockRecorder {
	return m.recorder
}

// AddNewTask mocks base method.
func (m *MockIAppStorage) AddNewTask(arg0 *datastruct.DBCreateTaskRequest) (*datastruct.CreateTaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewTask", arg0)
	ret0, _ := ret[0].(*datastruct.CreateTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewTask indicates an expected call of AddNewTask.
func (mr *MockIAppStorageMockRecorder) AddNewTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewTask", reflect.TypeOf((*MockIAppStorage)(nil).AddNewTask), arg0)
}

// AddNewTeam mocks base method.
func (m *MockIAppStorage) AddNewTeam(arg0 *datastruct.CreateTeamRequest) (*datastruct.CreateTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewTeam", arg0)
	ret0, _ := ret[0].(*datastruct.CreateTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewTeam indicates an expected call of AddNewTeam.
func (mr *MockIAppStorageMockRecorder) AddNewTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewTeam", reflect.TypeOf((*MockIAppStorage)(nil).AddNewTeam), arg0)
}

// AddTaskComment mocks base method.
func (m *MockIAppStorage) AddTaskComment(arg0 *datastruct.AddTaskCommentRequest) (*datastruct.AddTaskCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskComment", arg0)
	ret0, _ := ret[0].(*datastruct.AddTaskCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTaskComment indicates an expected call of AddTaskComment.
func (mr *MockIAppStorageMockRecorder) AddTaskComment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskComment", reflect.TypeOf((*MockIAppStorage)(nil).AddTaskComment), arg0)
}

// AddUserToUserTeam mocks base method.
func (m *MockIAppStorage) AddUserToUserTeam(arg0 *datastruct.DBInviteUserToTeamRequest) (*datastruct.InviteUserToTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToUserTeam", arg0)
	ret0, _ := ret[0].(*datastruct.InviteUserToTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserToUserTeam indicates an expected call of AddUserToUserTeam.
func (mr *MockIAppStorageMockRecorder) AddUserToUserTeam(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToUserTeam", reflect.TypeOf((*MockIAppStorage)(nil).AddUserToUserTeam), arg0)
}

// GetTaskHistory mocks base method.
func (m *MockIAppStorage) GetTaskHistory(arg0 *datastruct.GetTaskHistoryRequest) (*datastruct.GetTaskHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistory", arg0)
	ret0, _ := ret[0].(*datastruct.GetTaskHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistory indicates an expected call of GetTaskHistory.
func (mr *MockIAppStorageMockRecorder) GetTaskHistory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistory", reflect.TypeOf((*MockIAppStorage)(nil).GetTaskHistory), arg0)
}

// GetTasks mocks base method.
func (m *MockIAppStorage) GetTasks(arg0 *datastruct.GetTasksRequest) (*datastruct.GetTasksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", arg0)
	ret0, _ := ret[0].(*datastruct.GetTasksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockIAppStorageMockRecorder) GetTasks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockIAppStorage)(nil).GetTasks), arg0)
}

// GetUserTeams mocks base method.
func (m *MockIAppStorage) GetUserTeams(arg0 int64) (*datastruct.ListUserTeamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTeams", arg0)
	ret0, _ := ret[0].(*datastruct.ListUserTeamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTeams indicates an expected call of GetUserTeams.
func (mr *MockIAppStorageMockRecorder) GetUserTeams(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTeams", reflect.TypeOf((*MockIAppStorage)(nil).GetUserTeams), arg0)
}

// UpdateTask mocks base method.
func (m *MockIAppStorage) UpdateTask(arg0 *datastruct.DBUpdateTaskRequest) (*datastruct.UpdateTaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0)
	ret0, _ := ret[0].(*datastruct.UpdateTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockIAppStorageMockRecorder) UpdateTask(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockIAppStorage)(nil).UpdateTask), arg0)
}

// MockISecretProvider is a mock of ISecretProvider interface.
type MockISecretProvider struct {
	ctrl     *gomock.Controller
	recorder *MockISecretProviderMockRecorder
}

// MockISecretProviderMockRecorder is the mock recorder for MockISecretProvider.
type MockISecretProviderMockRecorder struct {
	mock *MockISecretProvider
}

// NewMockISecretProvider creates a new mock instance.
func NewMockISecretProvider(ctrl *gomock.Controller) *MockISecretProvider {
	mock := &MockISecretProvider{ctrl: ctrl}
	mock.recorder = &MockISecretProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISecretProvider) EXPECT() *MockISecretProviderMockRecorder {
	return m.recorder
}

// ReadSecret mocks base method.
func (m *MockISecretProvider) ReadSecret(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSecret", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSecret indicates an expected call of ReadSecret.
func (mr *MockISecretProviderMockRecorder) ReadSecret(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSecret", reflect.TypeOf((*MockISecretProvider)(nil).ReadSecret), arg0)
}
